import type { Asset } from "./types";

export const demoAssets: Asset[] = [
  {
    id: "asset_001",
    workspaceId: "workspace_demo",
    name: "Production Web",
    type: "APPLICATION",
    environment: "PRODUCTION",
    status: "ACTIVE",
    owner: "platform-team",
    criticality: 5,
    identifier: "web-prod-01",
    tags: ["internet-facing", "customer"],
    lastScannedAt: "2026-08-13T05:30:00.000Z",
  },
  {
    id: "asset_002",
    workspaceId: "workspace_demo",
    name: "Public API",
    type: "API",
    environment: "PRODUCTION",
    status: "ACTIVE",
    owner: "api-team",
    criticality: 5,
    identifier: "api-prod-01",
    tags: ["api", "customer"],
    lastScannedAt: "2026-08-13T04:45:00.000Z",
  },
  {
    id: "asset_003",
    workspaceId: "workspace_demo",
    name: "DevSecOps Repository",
    type: "REPOSITORY",
    environment: "DEVELOPMENT",
    status: "ACTIVE",
    owner: "security-team",
    criticality: 4,
    identifier: "github/solid-fiesta",
    tags: ["source", "ci-cd"],
    lastScannedAt: "2026-08-12T21:20:00.000Z",
  },
  {
    id: "asset_004",
    workspaceId: "workspace_demo",
    name: "Production Container",
    type: "CONTAINER",
    environment: "PRODUCTION",
    status: "ACTIVE",
    owner: "platform-team",
    criticality: 4,
    identifier: "solid-fiesta:prod",
    tags: ["container", "runtime"],
    lastScannedAt: "2026-08-13T03:10:00.000Z",
  },
];
